-- NOVA vocabulary.
--
-- NOVA names the customer a Passenger and the driver a Rider. This schema named
-- the customer a rider and the driver a driver, so the two words swap places.
--
-- Done in one migration on purpose. A half-finished rename leaves `rider`
-- meaning the customer in one function and the driver in the next, and the first
-- bug that causes is an RLS policy handing someone else's location to the wrong
-- person. Every function body is recreated here because Postgres stores them as
-- text and re-resolves names at execution: a column rename alone would leave
-- them parsing fine and failing at runtime.
--
-- Generated by scripts/gen-nova-rename.mjs.

-- 1. Enum values. Order matters: the customer's value must vacate the name
-- `rider` before the driver's value can take it.
alter type user_role rename value 'rider' to 'passenger';
alter type user_role rename value 'driver' to 'rider';

alter type trip_state rename value 'cancelled_by_rider' to 'cancelled_by_passenger';
alter type trip_state rename value 'cancelled_by_driver' to 'cancelled_by_rider';

alter type sos_source rename value 'rider' to 'passenger';
alter type sos_source rename value 'driver' to 'rider';

alter type trip_actor rename value 'rider' to 'passenger';
alter type trip_actor rename value 'driver' to 'rider';

-- This type's NAME carries the old vocabulary even though its values do not.
alter type driver_status rename to rider_status;

alter type trip_state rename value 'no_drivers' to 'no_riders';

-- Not caught by the column sweep because it is not named driver_id, but the
-- function bodies below already say min_rider_balance_rwf - without this they
-- parse and then fail at call time, which check_function_bodies = off would
-- have let through silently.
alter table public.platform_settings
  rename column min_driver_balance_rwf to min_rider_balance_rwf;

-- 1b. Two policies call functions that are recreated further down, and Postgres
-- refuses to drop a function a policy depends on. They come off here and go
-- back on at the end, with their expressions swapped.
drop policy presence_owner_all on public.driver_presence;
drop policy profiles_select_trip_partner on public.profiles;

-- 2. Tables.
alter table public.drivers rename to riders;
alter table public.driver_presence rename to rider_presence;
alter table public.driver_documents rename to rider_documents;

-- 3. Columns. Same ordering rule as the enums: within one table the customer
-- column must be renamed before the driver column claims its name.
alter table public.trips rename column rider_id to passenger_id;
alter table public.trips rename column driver_id to rider_id;

alter table public.trip_ratings rename column rider_id to passenger_id;
alter table public.trip_ratings rename column driver_id to rider_id;

alter table public.fare_quotes rename column rider_id to passenger_id;
alter table public.saved_places rename column rider_id to passenger_id;

alter table public.rider_presence rename column driver_id to rider_id;
alter table public.rider_documents rename column driver_id to rider_id;
alter table public.ledger_entries rename column driver_id to rider_id;
alter table public.trip_offers rename column driver_id to rider_id;
alter table public.vehicles rename column driver_id to rider_id;


-- 4. Indexes, customer-named ones first so their names are free.
alter index public.saved_places_rider_idx rename to saved_places_passenger_idx;
alter index public.trips_rider_idx rename to trips_passenger_idx;
alter index public.driver_documents_driver_id_kind_key rename to rider_documents_rider_id_kind_key;
alter index public.driver_documents_driver_idx rename to rider_documents_rider_idx;
alter index public.driver_documents_pkey rename to rider_documents_pkey;
alter index public.driver_presence_dispatchable_idx rename to rider_presence_dispatchable_idx;
alter index public.driver_presence_heartbeat_idx rename to rider_presence_heartbeat_idx;
alter index public.driver_presence_pkey rename to rider_presence_pkey;
alter index public.drivers_pkey rename to riders_pkey;
alter index public.ledger_entries_driver_idx rename to ledger_entries_rider_idx;
alter index public.trip_offers_one_live_per_driver rename to trip_offers_one_live_per_rider;
alter index public.trip_ratings_driver_idx rename to trip_ratings_rider_idx;
alter index public.trips_driver_idx rename to trips_rider_idx;
alter index public.vehicles_driver_id_plate_key rename to vehicles_rider_id_plate_key;
alter index public.vehicles_driver_idx rename to vehicles_rider_idx;
alter index public.vehicles_one_active_per_driver rename to vehicles_one_active_per_rider;

-- 5. Policy names, in the same two passes. The expressions follow the
-- column renames above automatically; only the names need moving.
alter policy driver_documents_owner_insert on public.rider_documents rename to rider_documents_owner_insert;
alter policy driver_documents_owner_select on public.rider_documents rename to rider_documents_owner_select;
alter policy driver_documents_owner_update on public.rider_documents rename to rider_documents_owner_update;
alter policy drivers_insert_self on public.riders rename to riders_insert_self;
alter policy drivers_select_self on public.riders rename to riders_select_self;
alter policy track_points_insert_driver on public.trip_track_points rename to track_points_insert_rider;

-- 6. Function bodies.
--
-- check_function_bodies off for this section: the functions are recreated in
-- alphabetical order, so can_go_online_internal is rebuilt before the
-- rider_balance_internal it calls exists under its new name. Postgres validates
-- a SQL function's body at creation and would reject it. Turning the check off
-- lets them be created in any order and resolve at call time; it is restored
-- immediately afterwards, and the pgTAP suite is what proves they all still
-- resolve.
set local check_function_bodies = off;

drop function if exists public.accept_offer(p_offer_id uuid, p_idempotency_key text);
CREATE OR REPLACE FUNCTION public.accept_offer(p_offer_id uuid, p_idempotency_key text)
 RETURNS trips
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_offer public.trip_offers;
begin
  update public.trip_offers
     set outcome = 'accepted'
   where id = p_offer_id
     and rider_id = auth.uid()
     and outcome is null
     and expires_at > now()
  returning * into v_offer;

  if not found then
    raise exception 'offer_not_available' using errcode = '42501';
  end if;

  return public.trip_transition(v_offer.trip_id, 'accepted', p_idempotency_key,
                                jsonb_build_object('offer_id', p_offer_id));
end;
$function$;

drop function if exists public.assign_driver_to_trip(p_trip_id uuid, p_driver_id uuid, p_idempotency_key text);
CREATE OR REPLACE FUNCTION public.assign_rider_to_trip(p_trip_id uuid, p_rider_id uuid, p_idempotency_key text)
 RETURNS trips
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_trip public.trips;
begin
  select * into v_trip from public.trips where id = p_trip_id for update;
  if not found then
    raise exception 'trip_not_found' using errcode = 'P0002';
  end if;

  if not exists (
    select 1 from public.riders
     where id = p_rider_id and verification = 'verified'
  ) then
    raise exception 'rider_not_verified' using errcode = '42501';
  end if;

  -- The replay check has to happen HERE, before the rider_id write, not inside
  -- trip_transition_system() afterwards. The lock taken above is what makes it
  -- race-safe, exactly as in trip_transition().
  if exists (
    select 1 from public.trip_events
     where trip_id = p_trip_id and idempotency_key = p_idempotency_key
  ) then
    return v_trip;
  end if;

  perform set_config('gera.in_transition', '1', true);
  update public.trips set rider_id = p_rider_id where id = p_trip_id;
  perform set_config('gera.in_transition', '0', true);

  -- The rider goes into the event meta: an offer log that does not record who
  -- was offered the trip cannot answer the one question it exists to answer.
  return public.trip_transition_system(
    p_trip_id, 'offered', p_idempotency_key,
    jsonb_build_object('rider_id', p_rider_id)
  );
end;
$function$;

drop function if exists public.can_go_online(p_driver_id uuid);
CREATE OR REPLACE FUNCTION public.can_go_online(p_rider_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if p_rider_id <> auth.uid() and auth.uid() is not null then
    raise exception 'not_your_balance' using errcode = '42501';
  end if;

  return public.can_go_online_internal(p_rider_id);
end;
$function$;

drop function if exists public.can_go_online_internal(p_driver_id uuid);
CREATE OR REPLACE FUNCTION public.can_go_online_internal(p_rider_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select public.rider_balance_internal(p_rider_id)
         >= (select min_rider_balance_rwf from public.platform_settings);
$function$;

drop function if exists public.complete_trip(p_trip_id uuid, p_actual_distance_m integer, p_idempotency_key text);
CREATE OR REPLACE FUNCTION public.complete_trip(p_trip_id uuid, p_actual_distance_m integer, p_idempotency_key text)
 RETURNS trips
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_trip       public.trips;
  v_policy     public.fare_policies;
  v_total      integer;
  v_commission integer;
begin
  -- Argument validation before the lock, as in 0013.
  if p_actual_distance_m is null or p_actual_distance_m < 0 then
    raise exception 'negative_distance' using errcode = '22023';
  end if;

  select * into v_trip from public.trips where id = p_trip_id for update;
  if not found then
    raise exception 'trip_not_found' using errcode = 'P0002';
  end if;

  -- Authorization BEFORE the idempotent early return. An unchecked early return
  -- on a security-definer function hands the whole trip row - passenger_id, both
  -- labels, and the free-text pickup_note - to anyone who supplies a trip id and
  -- a used idempotency key. Migration 0006 guards trip_transition() the same way
  -- and for the same reason. Only the rider may complete a trip.
  if v_trip.rider_id is null or v_trip.rider_id <> auth.uid() then
    raise exception 'not_the_rider' using errcode = '42501';
  end if;

  -- Idempotent: a replayed completion must not debit commission twice.
  if exists (
    select 1 from public.trip_events
     where trip_id = p_trip_id and idempotency_key = p_idempotency_key
  ) then
    return v_trip;
  end if;

  -- The locked price is the trip's own, written at creation from the quote. A
  -- trip with no quote has no price to honour, and inventing one is how a passenger
  -- gets charged a number nobody quoted them.
  if v_trip.quoted_amount_rwf is null or v_trip.quote_id is null then
    raise exception 'trip_has_no_quote' using errcode = '22023';
  end if;

  -- Priced under the policy the trip was QUOTED under, never the one in force
  -- now: a rate change between quote and completion must not reach this trip.
  select * into v_policy from public.fare_policy_for_quote(v_trip.quote_id);
  if v_policy.id is null then
    raise exception 'quote_policy_not_found' using errcode = '22023';
  end if;

  v_total := public.final_fare_rwf(
    v_trip.quoted_amount_rwf,
    coalesce(v_trip.quoted_distance_m, 0),
    p_actual_distance_m,
    v_policy.per_km_rwf
  );
  v_commission := public.commission_rwf(v_total, v_policy.commission_pct);

  perform set_config('gera.in_transition', '1', true);
  update public.trips
     set actual_distance_m = p_actual_distance_m
   where id = p_trip_id;
  perform set_config('gera.in_transition', '0', true);

  -- Raises if the edge is illegal or the caller is not the rider.
  v_trip := public.trip_transition(
    p_trip_id, 'completed', p_idempotency_key,
    jsonb_build_object(
      'total_rwf', v_total,
      'commission_rwf', v_commission,
      'policy_id', v_policy.id
    )
  );

  insert into public.ledger_entries (rider_id, trip_id, kind, amount_rwf, memo)
  values (v_trip.rider_id, p_trip_id, 'commission_debit', v_commission,
          'commission on trip ' || p_trip_id);

  return v_trip;
end;
$function$;

drop function if exists public.create_trip_from_quote(p_quote_id uuid, p_pickup geography, p_pickup_label text, p_pickup_note text, p_dropoff geography, p_dropoff_label text);
CREATE OR REPLACE FUNCTION public.create_trip_from_quote(p_quote_id uuid, p_pickup geography, p_pickup_label text, p_pickup_note text, p_dropoff geography, p_dropoff_label text)
 RETURNS trips
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_quote public.fare_quotes;
  v_trip  public.trips;
begin
  if auth.uid() is null then
    raise exception 'unauthenticated' using errcode = '42501';
  end if;

  select * into v_quote from public.fare_quotes where id = p_quote_id;
  if not found then
    raise exception 'quote_not_found' using errcode = 'P0002';
  end if;

  if v_quote.passenger_id <> auth.uid() then
    raise exception 'quote_not_yours' using errcode = '42501';
  end if;

  if v_quote.expires_at <= now() then
    raise exception 'quote_expired' using errcode = '22023';
  end if;

  insert into public.trips
    (passenger_id, vehicle_class, state, pickup, pickup_label, pickup_note,
     dropoff, dropoff_label, quoted_distance_m, quoted_duration_s,
     quote_id, quoted_amount_rwf)
  values
    (auth.uid(), v_quote.vehicle_class, 'requested', p_pickup, p_pickup_label,
     nullif(btrim(coalesce(p_pickup_note, '')), ''),
     p_dropoff, p_dropoff_label, v_quote.distance_m, v_quote.duration_s,
     v_quote.id, v_quote.amount_rwf)
  returning * into v_trip;

  return v_trip;
end;
$function$;

drop function if exists public.create_trip_offer(p_trip_id uuid, p_driver_id uuid, p_rank integer, p_eta_seconds integer, p_ttl_seconds integer, p_idempotency_key text);
CREATE OR REPLACE FUNCTION public.create_trip_offer(p_trip_id uuid, p_rider_id uuid, p_rank integer, p_eta_seconds integer, p_ttl_seconds integer, p_idempotency_key text)
 RETURNS trip_offers
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_offer public.trip_offers;
begin
  if p_ttl_seconds <= 0 then
    raise exception 'ttl_must_be_positive' using errcode = '22023';
  end if;

  perform 1 from public.trips where id = p_trip_id for update;
  if not found then
    raise exception 'trip_not_found' using errcode = 'P0002';
  end if;

  -- Idempotent: a retried dispatch must not create a second live offer. LIVE,
  -- not merely unresolved - see the note above.
  select * into v_offer from public.trip_offers
   where trip_id = p_trip_id and outcome is null and expires_at > now();
  if found then
    return v_offer;
  end if;

  if exists (
    select 1 from public.trip_offers
     where rider_id = p_rider_id and outcome is null
  ) then
    raise exception 'rider_already_offered' using errcode = '42501';
  end if;

  if exists (
    select 1 from public.trips
     where rider_id = p_rider_id
       and id <> p_trip_id
       and state in ('offered', 'accepted', 'arrived', 'in_progress')
  ) then
    raise exception 'rider_already_committed' using errcode = '42501';
  end if;

  insert into public.trip_offers (trip_id, rider_id, rank, eta_seconds, expires_at)
  values (p_trip_id, p_rider_id, p_rank, p_eta_seconds,
          now() + make_interval(secs => p_ttl_seconds))
  returning * into v_offer;

  perform public.assign_rider_to_trip(p_trip_id, p_rider_id, p_idempotency_key);

  return v_offer;
end;
$function$;

drop function if exists public.credit_driver_wallet(p_driver_id uuid, p_amount_rwf integer, p_reference text);
CREATE OR REPLACE FUNCTION public.credit_rider_wallet(p_rider_id uuid, p_amount_rwf integer, p_reference text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if p_amount_rwf is null or p_amount_rwf <= 0 then
    raise exception 'amount_must_be_positive' using errcode = '22023';
  end if;
  if p_reference is null or length(btrim(p_reference)) = 0 then
    -- An unreferenced credit is indistinguishable from an invented one.
    raise exception 'reference_required' using errcode = '22023';
  end if;

  insert into public.ledger_entries (rider_id, kind, amount_rwf, memo)
  values (p_rider_id, 'topup_credit', p_amount_rwf, p_reference);

  return public.rider_balance(p_rider_id);
end;
$function$;

drop function if exists public.decline_offer(p_offer_id uuid);
CREATE OR REPLACE FUNCTION public.decline_offer(p_offer_id uuid)
 RETURNS trip_offers
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_offer public.trip_offers;
begin
  update public.trip_offers
     set outcome = 'declined'
   where id = p_offer_id
     and rider_id = auth.uid()
     and outcome is null
     and expires_at > now()
  returning * into v_offer;

  if not found then
    raise exception 'offer_not_available' using errcode = '42501';
  end if;

  -- No exception handler: if the advance cannot happen the decline must not
  -- stand either, because a recorded decline with the trip left in `offered` is
  -- precisely the corruption this migration exists to remove. The rider
  -- retries; nothing is stranded in the meantime.
  perform public.offer_next_candidate(v_offer.trip_id);

  return v_offer;
end;
$function$;

drop function if exists public.dispatch_pending_trips();
CREATE OR REPLACE FUNCTION public.dispatch_pending_trips()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  -- A tick's work is bounded so a backlog cannot make one run unbounded; the
  -- next tick five seconds later takes the rest.
  v_batch constant integer := 50;
  v_trip  record;
  v_count integer := 0;
begin
  for v_trip in
    select t.id
      from public.trips t
     where t.state = 'requested'
       and not exists (
         select 1 from public.trip_offers o
          where o.trip_id = t.id and o.outcome is null
       )
     order by t.created_at
     limit v_batch
  loop
    begin
      perform public.offer_next_candidate(v_trip.id);
      v_count := v_count + 1;
    exception when others then
      -- One undispatchable trip must not abort the rest of the tick. Without
      -- this, a single bad row blocks every waiting passenger behind it.
      raise warning 'dispatch_pending_trips: trip % failed: %', v_trip.id, sqlerrm;
    end;
  end loop;

  return v_count;
end;
$function$;

drop function if exists public.driver_balance(p_driver_id uuid);
CREATE OR REPLACE FUNCTION public.rider_balance(p_rider_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if p_rider_id <> auth.uid() and auth.uid() is not null then
    raise exception 'not_your_balance' using errcode = '42501';
  end if;

  return public.rider_balance_internal(p_rider_id);
end;
$function$;

drop function if exists public.driver_balance_internal(p_driver_id uuid);
CREATE OR REPLACE FUNCTION public.rider_balance_internal(p_rider_id uuid)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(sum(
    case when kind in ('topup_credit', 'adjustment_credit')
         then amount_rwf else -amount_rwf end
  ), 0)::integer
    from public.ledger_entries
   where rider_id = p_rider_id;
$function$;

drop function if exists public.find_candidate_drivers(p_pickup geography, p_class vehicle_class, p_radius_m integer, p_limit integer);
CREATE OR REPLACE FUNCTION public.find_candidate_riders(p_pickup geography, p_class vehicle_class, p_radius_m integer, p_limit integer)
 RETURNS TABLE(rider_id uuid, distance_m double precision)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select p.rider_id,
         st_distance(p.position, p_pickup) as distance_m
    from public.rider_presence p
    join public.riders d on d.id = p.rider_id
   where p.status = 'online'
     and p.vehicle_class = p_class
     and p.position is not null
     -- A rider whose app died must not be offered a trip. Spec 6: the server
     -- decides a rider is gone, never the client.
     and p.heartbeat_at > now() - interval '30 seconds'
     and d.verification = 'verified'
     -- Spec 3.5, enforced at the point of dispatch rather than only at the
     -- moment of going online. A rider whose wallet fell below the minimum
     -- mid-shift stops being dispatchable immediately, whether or not they ever
     -- write `status` again.
     and public.can_go_online_internal(p.rider_id)
     and st_dwithin(p.position, p_pickup, p_radius_m)
     -- Not already committed to another live trip.
     and not exists (
       select 1 from public.trips t
        where t.rider_id = p.rider_id
          and t.state in ('offered', 'accepted', 'arrived', 'in_progress')
     )
   order by st_distance(p.position, p_pickup)
   limit p_limit;
$function$;

drop function if exists public.find_candidates_for_trip(p_trip_id uuid, p_radius_m integer, p_limit integer);
CREATE OR REPLACE FUNCTION public.find_candidates_for_trip(p_trip_id uuid, p_radius_m integer, p_limit integer)
 RETURNS TABLE(rider_id uuid, distance_m double precision)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select c.rider_id, c.distance_m
    from public.trips t
    cross join lateral public.find_candidate_riders(
      t.pickup, t.vehicle_class, p_radius_m, p_limit) c
   where t.id = p_trip_id;
$function$;

drop function if exists public.is_terminal(p_state trip_state);
CREATE OR REPLACE FUNCTION public.is_terminal(p_state trip_state)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select p_state in (
    'completed', 'cancelled_by_passenger', 'cancelled_by_rider', 'expired', 'no_riders'
  );
$function$;

drop function if exists public.my_documents();
CREATE OR REPLACE FUNCTION public.my_documents()
 RETURNS TABLE(kind document_kind, status document_status, note text, uploaded boolean)
 LANGUAGE sql
 STABLE
AS $function$
  select k.kind,
         coalesce(d.status, 'pending'::document_status),
         d.note,
         d.id is not null
    from unnest(enum_range(null::document_kind)) as k(kind)
    left join public.rider_documents d
      on d.kind = k.kind and d.rider_id = auth.uid()
   order by k.kind;
$function$;

drop function if exists public.notify_user(p_user_id uuid, p_title text, p_body text, p_data jsonb);
CREATE OR REPLACE FUNCTION public.notify_user(p_user_id uuid, p_title text, p_body text, p_data jsonb DEFAULT '{}'::jsonb)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_token text;
  v_sent  integer := 0;
begin
  for v_token in
    select token from public.device_tokens where user_id = p_user_id
  loop
    -- An Expo token has a fixed shape. Posting anything else to Expo just
    -- burns a request, and a malformed row should not become traffic.
    if v_token like 'ExponentPushToken[%]' or v_token like 'ExpoPushToken[%]' then
      perform net.http_post(
        url := 'https://exp.host/--/api/v2/push/send',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Accept', 'application/json'),
        body := jsonb_build_object(
          'to', v_token,
          'title', p_title,
          'body', p_body,
          'sound', 'default',
          -- An offer that arrives quietly is an offer the rider misses.
          'priority', 'high',
          'channelId', 'offers',
          'data', p_data)
      );
      v_sent := v_sent + 1;
    end if;
  end loop;

  return v_sent;
end;
$function$;

drop function if exists public.offer_next_candidate(p_trip_id uuid);
CREATE OR REPLACE FUNCTION public.offer_next_candidate(p_trip_id uuid)
 RETURNS trip_offers
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  -- The bound that makes dispatch terminate. Three offers at a 15s TTL is about
  -- as long as a passenger will sit watching a spinner before they give up anyway;
  -- telling them `no_riders` is the honest answer.
  v_max_attempts constant integer := 3;
  -- The widest stage of DISPATCH_RADII_M. The sweeper does not walk the stages
  -- the way supabase/functions/dispatch does: a re-offer is already late, so it
  -- looks as far as dispatch ever would, in one pass.
  v_radius_m     constant integer := 4000;
  -- Deep enough that skipping the riders who already saw this trip still
  -- leaves someone to offer it to.
  v_scan_limit   constant integer := 10;
  v_trip      public.trips;
  v_rider_id uuid;
  v_attempt   integer;
begin
  -- Lock first. A slow sweep overlapping the next cron tick must not let both
  -- advance the same trip.
  select * into v_trip from public.trips where id = p_trip_id for update;
  if not found then
    raise exception 'trip_not_found' using errcode = 'P0002';
  end if;

  -- Anything else is no longer dispatch's to touch: accepted, cancelled,
  -- completed, or already terminal.
  if v_trip.state not in ('requested', 'offered') then
    return null;
  end if;

  -- A live offer means the previous one has not actually lapsed. Advancing now
  -- would revoke an offer a rider is still looking at.
  if exists (
    select 1 from public.trip_offers
     where trip_id = p_trip_id and outcome is null
  ) then
    return null;
  end if;

  -- dispatch_attempts is not trips.state, so trips_guard_state_trg does not
  -- gate it and no in_transition flag is needed for this write.
  --
  -- The counter is seeded from the offers that actually exist, not taken on
  -- trust: the FIRST offer is made by supabase/functions/dispatch, which never
  -- passes through here, so counting only what this function did would make
  -- that offer free and hand the rank it already used to a second rider. With
  -- the seed, dispatch_attempts is exactly "offers made for this trip", however
  -- they were made, and `rank` below reads as the Nth offer.
  update public.trips
     set dispatch_attempts = greatest(
           dispatch_attempts,
           (select count(*) from public.trip_offers where trip_id = p_trip_id)
         ) + 1
   where id = p_trip_id
  returning dispatch_attempts into v_attempt;

  if v_attempt > v_max_attempts then
    perform public.trip_transition_system(
      p_trip_id, 'no_riders',
      'dispatch-exhausted-' || p_trip_id::text,
      jsonb_build_object('reason', 'max_attempts', 'attempts', v_attempt));
    return null;
  end if;

  -- Clear the outgoing rider BEFORE searching. find_candidate_riders excludes
  -- anyone committed to a trip in 'offered', and this trip is still 'offered'
  -- with rider_id set to the rider who just let the offer lapse - leaving it
  -- set is precisely what made that rider permanently unmatchable.
  --
  -- set_config's third argument scopes the flag to the TRANSACTION, not the
  -- statement, so it is lowered to '0' immediately: leaving it raised would
  -- exempt every later write in this transaction from trips_guard_state_trg,
  -- including ones this function knows nothing about.
  if v_trip.rider_id is not null then
    perform set_config('gera.in_transition', '1', true);
    update public.trips set rider_id = null where id = p_trip_id;
    perform set_config('gera.in_transition', '0', true);
  end if;

  -- Ordered by straight-line distance, not ETA - see the DESIGN NOTE at the top
  -- of this migration. Skipping riders who already had an offer for THIS trip
  -- is what makes the chain advance; without it the nearest rider is re-offered
  -- the trip they just ignored, on every tick, until the attempt bound fires.
  select c.rider_id into v_rider_id
    from public.find_candidate_riders(
           v_trip.pickup, v_trip.vehicle_class, v_radius_m, v_scan_limit) c
   where not exists (
     select 1 from public.trip_offers o
      where o.trip_id = p_trip_id and o.rider_id = c.rider_id
   )
   -- Belt and braces against the sweeper ever raising: a rider holding a live
   -- offer is refused by create_trip_offer, and a raise inside the sweep rolls
   -- back the timed_out marks for every other trip in the same tick.
   and not exists (
     select 1 from public.trip_offers o2
      where o2.rider_id = c.rider_id and o2.outcome is null
   )
   order by c.distance_m
   limit 1;

  if v_rider_id is null then
    perform public.trip_transition_system(
      p_trip_id, 'no_riders',
      'dispatch-no-candidates-' || p_trip_id::text || '-' || v_attempt::text,
      jsonb_build_object('reason', 'no_candidates', 'attempts', v_attempt));
    return null;
  end if;

  -- eta_seconds is null by design on this path: the sweeper has no ETA
  -- provider, and inventing one here would be a second, silent copy of
  -- AVERAGE_SPEED_MPS living in SQL. A null eta is honest about which path
  -- created the offer.
  return public.create_trip_offer(
    p_trip_id, v_rider_id, v_attempt, null,
    public.offer_ttl_seconds(),
    'reoffer-' || p_trip_id::text || '-' || v_attempt::text);
end;
$function$;

drop function if exists public.presence_status_now(p_driver_id uuid);
CREATE OR REPLACE FUNCTION public.presence_status_now(p_rider_id uuid)
 RETURNS rider_status
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select status from public.rider_presence where rider_id = p_rider_id;
$function$;

drop function if exists public.publish_track_point(p_trip_id uuid, p_lng double precision, p_lat double precision, p_accuracy_m real);
CREATE OR REPLACE FUNCTION public.publish_track_point(p_trip_id uuid, p_lng double precision, p_lat double precision, p_accuracy_m real DEFAULT NULL::real)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_trip public.trips;
begin
  select * into v_trip from public.trips where id = p_trip_id;

  -- Authorise before anything else, and answer the same way for "no such trip"
  -- and "not your trip".
  if not found or v_trip.rider_id is distinct from auth.uid() then
    raise exception 'trip_not_found' using errcode = 'P0002';
  end if;

  -- A finished trip is not a tracking channel. Without this a rider could
  -- keep publishing their position long after dropping the passenger off, and the
  -- passenger could keep reading it.
  if v_trip.state not in ('accepted', 'arrived', 'in_progress') then
    return;
  end if;

  insert into public.trip_track_points (trip_id, position, accuracy_m, recorded_at)
  values (
    p_trip_id,
    st_setsrid(st_point(p_lng, p_lat), 4326)::geography,
    p_accuracy_m,
    now()
  );
end;
$function$;

-- push_on_offer: body only, replaced in place.
CREATE OR REPLACE FUNCTION public.push_on_offer()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_trip public.trips;
begin
  select * into v_trip from public.trips where id = new.trip_id;
  if not found then return new; end if;

  perform public.notify_user(
    new.rider_id,
    'New trip · ' || coalesce(v_trip.quoted_amount_rwf::text, '—') || ' RWF',
    coalesce(v_trip.pickup_label, 'Pickup') || ' → ' || coalesce(v_trip.dropoff_label, 'Destination'),
    jsonb_build_object('kind', 'offer', 'offerId', new.id, 'tripId', new.trip_id));

  return new;
end;
$function$;

-- push_on_trip_state: body only, replaced in place.
CREATE OR REPLACE FUNCTION public.push_on_trip_state()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.state = old.state then return new; end if;

  if new.state = 'accepted' then
    perform public.notify_user(new.passenger_id, 'Rider on the way',
      'Your rider is coming to ' || coalesce(new.pickup_label, 'the pickup') || '.',
      jsonb_build_object('kind', 'trip', 'tripId', new.id, 'state', new.state));

  elsif new.state = 'arrived' then
    perform public.notify_user(new.passenger_id, 'Your rider is here',
      'Head out to meet them.',
      jsonb_build_object('kind', 'trip', 'tripId', new.id, 'state', new.state));

  elsif new.state = 'completed' then
    perform public.notify_user(new.passenger_id, 'Trip complete',
      'Pay ' || coalesce(new.quoted_amount_rwf::text, '—') || ' RWF in cash.',
      jsonb_build_object('kind', 'trip', 'tripId', new.id, 'state', new.state));

  elsif new.state = 'no_riders' then
    perform public.notify_user(new.passenger_id, 'No riders nearby',
      'Nobody was free. Try again in a few minutes.',
      jsonb_build_object('kind', 'trip', 'tripId', new.id, 'state', new.state));

  elsif new.state = 'cancelled_by_passenger' and new.rider_id is not null then
    perform public.notify_user(new.rider_id, 'Trip cancelled',
      'The passenger cancelled this trip.',
      jsonb_build_object('kind', 'trip', 'tripId', new.id, 'state', new.state));

  elsif new.state = 'cancelled_by_rider' then
    perform public.notify_user(new.passenger_id, 'Trip cancelled',
      'Your rider cancelled. Book again and we will find someone else.',
      jsonb_build_object('kind', 'trip', 'tripId', new.id, 'state', new.state));
  end if;

  return new;
end;
$function$;

drop function if exists public.raise_sos(p_trip_id uuid, p_lng double precision, p_lat double precision, p_note text);
CREATE OR REPLACE FUNCTION public.raise_sos(p_trip_id uuid DEFAULT NULL::uuid, p_lng double precision DEFAULT NULL::double precision, p_lat double precision DEFAULT NULL::double precision, p_note text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_trip   public.trips;
  v_source sos_source;
  v_id     uuid;
begin
  if auth.uid() is null then
    raise exception 'unauthenticated' using errcode = '28000';
  end if;

  v_source := 'passenger';

  if p_trip_id is not null then
    select * into v_trip from public.trips where id = p_trip_id;
    if found then
      if v_trip.rider_id = auth.uid() then
        v_source := 'rider';
      elsif v_trip.passenger_id <> auth.uid() then
        -- Not their trip. Still record the alert, just not against that trip -
        -- refusing to log because an id was wrong would be the wrong call here.
        p_trip_id := null;
      end if;
    else
      p_trip_id := null;
    end if;
  end if;

  insert into public.sos_alerts (trip_id, raised_by, source, position, note)
  values (
    p_trip_id,
    auth.uid(),
    v_source,
    case when p_lng is not null and p_lat is not null
         then st_setsrid(st_point(p_lng, p_lat), 4326)::geography
    end,
    p_note
  )
  returning id into v_id;

  return v_id;
end;
$function$;

drop function if exists public.rate_trip(p_trip_id uuid, p_rating smallint, p_comment text);
CREATE OR REPLACE FUNCTION public.rate_trip(p_trip_id uuid, p_rating smallint, p_comment text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_trip     public.trips;
  v_previous smallint;
begin
  if p_rating is null or p_rating < 1 or p_rating > 5 then
    raise exception 'rating_out_of_range' using errcode = '22023';
  end if;

  -- Authorise BEFORE reading anything back, and answer identically for "no
  -- such trip" and "not your trip" - the lookup-oracle defect this project has
  -- shipped twice already.
  select * into v_trip from public.trips where id = p_trip_id;
  if not found or v_trip.passenger_id <> auth.uid() then
    raise exception 'trip_not_found' using errcode = 'P0002';
  end if;

  if v_trip.state <> 'completed' then
    raise exception 'trip_not_completed' using errcode = '22023';
  end if;
  if v_trip.rider_id is null then
    raise exception 'trip_has_no_rider' using errcode = '22023';
  end if;

  select rating into v_previous from public.trip_ratings where trip_id = p_trip_id;

  insert into public.trip_ratings (trip_id, passenger_id, rider_id, rating, comment)
  values (p_trip_id, v_trip.passenger_id, v_trip.rider_id, p_rating, p_comment)
  on conflict (trip_id) do update
    set rating = excluded.rating,
        comment = excluded.comment,
        created_at = now();

  if v_previous is null then
    update public.riders
       set rating_sum = rating_sum + p_rating,
           rating_count = rating_count + 1
     where id = v_trip.rider_id;
  else
    -- A correction moves the sum by the difference. Adding again would let a
    -- passenger inflate a rider by re-rating.
    update public.riders
       set rating_sum = rating_sum + (p_rating - v_previous)
     where id = v_trip.rider_id;
  end if;
end;
$function$;

drop function if exists public.register_driver(p_first_name text, p_phone text, p_licence text, p_plate text, p_vest text, p_class vehicle_class);
CREATE OR REPLACE FUNCTION public.register_rider(p_first_name text, p_phone text, p_licence text, p_plate text, p_vest text, p_class vehicle_class)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  insert into public.profiles (id, role, first_name, phone)
  values (v_uid, 'rider', p_first_name, p_phone)
  on conflict (id) do update
     set role       = 'rider',
         first_name = excluded.first_name,
         phone      = excluded.phone,
         updated_at = now();

  -- `verification` is hardcoded and is deliberately NOT a parameter. Ops owns
  -- that value; a caller who could pass it would register themselves verified
  -- and walk straight into the dispatch index. An existing row keeps whatever
  -- verification ops already gave it - a re-submit must not silently demote a
  -- rider who is already approved, nor promote one who is not.
  insert into public.riders (id, verification, licence_number)
  values (v_uid, 'submitted', p_licence)
  on conflict (id) do update
     set licence_number = excluded.licence_number,
         updated_at     = now();

  insert into public.vehicles (rider_id, class, plate, vest_number, is_active)
  values (v_uid, p_class, p_plate, p_vest, false)
  on conflict (rider_id, plate) do update
     set class       = excluded.class,
         vest_number = excluded.vest_number;
end;
$function$;

drop function if exists public.review_document(p_driver_id uuid, p_kind document_kind, p_approve boolean, p_note text);
CREATE OR REPLACE FUNCTION public.review_document(p_rider_id uuid, p_kind document_kind, p_approve boolean, p_note text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update public.rider_documents
     set status = case when p_approve then 'approved'::document_status
                       else 'rejected'::document_status end,
         note = case when p_approve then null else p_note end,
         updated_at = now()
   where rider_id = p_rider_id and kind = p_kind;

  if not found then
    raise exception 'document_not_found' using errcode = 'P0002';
  end if;
end;
$function$;

drop function if exists public.review_queue();
CREATE OR REPLACE FUNCTION public.review_queue()
 RETURNS TABLE(rider_id uuid, first_name text, phone text, verification text, vehicle_class text, plate text, balance_rwf integer, documents jsonb, submitted_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select d.id,
         p.first_name,
         p.phone,
         d.verification::text,
         v.class::text,
         v.plate,
         public.rider_balance(d.id),
         coalesce(
           (select jsonb_object_agg(dd.kind::text,
                     jsonb_build_object('status', dd.status, 'path', dd.storage_path))
              from public.rider_documents dd
             where dd.rider_id = d.id),
           '{}'::jsonb),
         d.created_at
    from public.riders d
    join public.profiles p on p.id = d.id
    left join public.vehicles v on v.rider_id = d.id and v.is_active
   where d.verification <> 'verified'
   order by d.created_at;
$function$;

-- set_trip_payment_kind: body only, replaced in place.
CREATE OR REPLACE FUNCTION public.set_trip_payment_kind()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  select kind into new.payment_kind
    from public.payment_methods
   where user_id = new.passenger_id and is_default
   limit 1;

  -- No stored preference is the common case, and cash is the honest default.
  if new.payment_kind is null then
    new.payment_kind := 'cash';
  end if;

  return new;
end;
$function$;

drop function if exists public.shares_active_trip(p_other uuid);
CREATE OR REPLACE FUNCTION public.shares_active_trip(p_other uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.trips t
     where t.state in ('accepted', 'arrived', 'in_progress')
       and (
            (t.passenger_id = auth.uid()  and t.rider_id = p_other)
         or (t.rider_id = auth.uid() and t.passenger_id  = p_other)
       )
  );
$function$;

drop function if exists public.suspend_driver(p_driver_id uuid, p_reason text);
CREATE OR REPLACE FUNCTION public.suspend_rider(p_rider_id uuid, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update public.riders
     set verification = 'rejected', verification_notes = p_reason, updated_at = now()
   where id = p_rider_id;

  update public.rider_presence
     set status = 'offline', updated_at = now()
   where rider_id = p_rider_id;
end;
$function$;

drop function if exists public.trip_contact(p_trip_id uuid);
CREATE OR REPLACE FUNCTION public.trip_contact(p_trip_id uuid)
 RETURNS TABLE(counterparty text, display_name text, phone text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_trip  public.trips;
  v_other uuid;
  v_role  text;
begin
  -- Authorise first, and answer identically for "no such trip" and "not your
  -- trip", so this cannot be used to probe for trip ids.
  select * into v_trip from public.trips where id = p_trip_id;
  if not found then
    return;
  end if;

  if v_trip.passenger_id = auth.uid() then
    v_other := v_trip.rider_id;
    v_role  := 'rider';
  elsif v_trip.rider_id = auth.uid() then
    v_other := v_trip.passenger_id;
    v_role  := 'passenger';
  else
    return;
  end if;

  if v_other is null then
    return;
  end if;

  -- The time box. A completed or cancelled trip is not a contact list.
  if v_trip.state not in ('accepted', 'arrived', 'in_progress') then
    return;
  end if;

  return query
  select v_role, p.first_name, p.phone
    from public.profiles p
   where p.id = v_other;
end;
$function$;

drop function if exists public.trip_driver_card(p_trip_id uuid);
CREATE OR REPLACE FUNCTION public.trip_rider_card(p_trip_id uuid)
 RETURNS TABLE(first_name text, plate text, vest_number text, vehicle_class vehicle_class, rating numeric)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_passenger  uuid;
  v_rider uuid;
begin
  -- Authorise FIRST, and on the trip, not on the rider. Returning early on a
  -- missing rider before checking the caller is how a security definer
  -- function turns into a lookup oracle - the exact defect this project
  -- shipped twice, in trip_transition and complete_trip.
  select t.passenger_id, t.rider_id into v_passenger, v_rider
    from public.trips t where t.id = p_trip_id;

  if v_passenger is null or v_passenger <> auth.uid() then
    -- Not this passenger's trip, or no such trip. Same answer either way, so the
    -- caller cannot tell one from the other.
    return;
  end if;

  if v_rider is null then
    return;
  end if;

  return query
  select p.first_name,
         v.plate,
         v.vest_number,
         v.class,
         case when d.rating_count > 0
              then round(d.rating_sum::numeric / d.rating_count, 1)
              else null
         end
    from public.profiles p
    join public.riders d on d.id = p.id
    left join public.vehicles v on v.rider_id = p.id and v.is_active
   where p.id = v_rider;
end;
$function$;

drop function if exists public.trip_driver_position(p_trip_id uuid);
CREATE OR REPLACE FUNCTION public.trip_rider_position(p_trip_id uuid)
 RETURNS TABLE(lng double precision, lat double precision, recorded_at timestamp with time zone, metres_away double precision, eta_seconds integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_trip   public.trips;
  v_target geography;
begin
  select * into v_trip from public.trips where id = p_trip_id;
  if not found then
    return;
  end if;

  -- Both sides of a trip may see it; nobody else may.
  if v_trip.passenger_id <> auth.uid() and v_trip.rider_id is distinct from auth.uid() then
    return;
  end if;

  if v_trip.state not in ('accepted', 'arrived', 'in_progress') then
    return;
  end if;

  -- Before the passenger is aboard the rider is heading to the pickup; after, to
  -- the drop-off. The distance shown should be to wherever they are going.
  v_target := case
    when v_trip.state = 'in_progress' then v_trip.dropoff
    else v_trip.pickup
  end;

  return query
  select st_x(t.position::geometry),
         st_y(t.position::geometry),
         t.recorded_at,
         st_distance(t.position, v_target),
         -- 7.5 m/s is the same average the fare quote uses. One number, one
         -- meaning, rather than a second speed constant living here.
         greatest(30, (st_distance(t.position, v_target) / 7.5))::integer
    from public.trip_track_points t
   where t.trip_id = p_trip_id
   order by t.recorded_at desc
   limit 1;
end;
$function$;

drop function if exists public.trip_transition(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb);
CREATE OR REPLACE FUNCTION public.trip_transition(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb DEFAULT '{}'::jsonb)
 RETURNS trips
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_trip  public.trips;
  v_actor trip_actor;
begin
  select * into v_trip from public.trips where id = p_trip_id for update;
  if not found then
    raise exception 'trip_not_found' using errcode = 'P0002';
  end if;

  if v_trip.passenger_id = auth.uid() then
    v_actor := 'passenger';
  elsif v_trip.rider_id = auth.uid() then
    v_actor := 'rider';
  else
    raise exception 'not_a_participant' using errcode = '42501';
  end if;

  if exists (
    select 1 from public.trip_events
     where trip_id = p_trip_id and idempotency_key = p_idempotency_key
  ) then
    return v_trip;
  end if;

  if not public.is_legal_transition(v_trip.state, p_to, v_actor) then
    raise exception 'illegal_transition: % -> % by %', v_trip.state, p_to, v_actor
      using errcode = '23514';
  end if;

  insert into public.trip_events
    (trip_id, from_state, to_state, actor, actor_id, idempotency_key, meta)
  values
    (p_trip_id, v_trip.state, p_to, v_actor, auth.uid(), p_idempotency_key, p_meta);

  perform set_config('gera.in_transition', '1', true);

  update public.trips
     set state = p_to, updated_at = now()
   where id = p_trip_id
  returning * into v_trip;

  perform set_config('gera.in_transition', '0', true);

  return v_trip;
end;
$function$;

drop function if exists public.verify_driver(p_driver_id uuid);
CREATE OR REPLACE FUNCTION public.verify_rider(p_rider_id uuid)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_required integer;
  v_approved integer;
begin
  select count(*) into v_required from unnest(enum_range(null::document_kind));

  select count(*) into v_approved
    from public.rider_documents
   where rider_id = p_rider_id and status = 'approved';

  if v_approved < v_required then
    return format('refused: %s of %s documents approved', v_approved, v_required);
  end if;

  update public.riders set verification = 'verified', updated_at = now()
   where id = p_rider_id;

  if not found then
    raise exception 'rider_not_found' using errcode = 'P0002';
  end if;

  return 'verified';
end;
$function$;

set local check_function_bodies = on;

-- 7. Close every recreated function to PUBLIC before reopening any of it.
revoke all on function public.accept_offer(p_offer_id uuid, p_idempotency_key text) from public;
revoke all on function public.assign_rider_to_trip(p_trip_id uuid, p_rider_id uuid, p_idempotency_key text) from public;
revoke all on function public.can_go_online_internal(p_rider_id uuid) from public;
revoke all on function public.can_go_online(p_rider_id uuid) from public;
revoke all on function public.commission_rwf(p_fare_rwf integer, p_rate_pct numeric) from public;
revoke all on function public.complete_trip(p_trip_id uuid, p_actual_distance_m integer, p_idempotency_key text) from public;
revoke all on function public.create_trip_from_quote(p_quote_id uuid, p_pickup geography, p_pickup_label text, p_pickup_note text, p_dropoff geography, p_dropoff_label text) from public;
revoke all on function public.create_trip_offer(p_trip_id uuid, p_rider_id uuid, p_rank integer, p_eta_seconds integer, p_ttl_seconds integer, p_idempotency_key text) from public;
revoke all on function public.credit_rider_wallet(p_rider_id uuid, p_amount_rwf integer, p_reference text) from public;
revoke all on function public.current_fare_policy(p_class vehicle_class) from public;
revoke all on function public.decline_offer(p_offer_id uuid) from public;
revoke all on function public.dispatch_pending_trips() from public;
revoke all on function public.rider_balance_internal(p_rider_id uuid) from public;
revoke all on function public.rider_balance(p_rider_id uuid) from public;
revoke all on function public.expire_stale_offers() from public;
revoke all on function public.fare_policy_for_quote(p_quote_id uuid) from public;
revoke all on function public.final_fare_rwf(p_quoted_rwf integer, p_quoted_distance_m integer, p_actual_distance_m integer, p_per_km_rwf integer) from public;
revoke all on function public.find_candidate_riders(p_pickup geography, p_class vehicle_class, p_radius_m integer, p_limit integer) from public;
revoke all on function public.find_candidates_for_trip(p_trip_id uuid, p_radius_m integer, p_limit integer) from public;
revoke all on function public.is_legal_transition(p_from trip_state, p_to trip_state, p_actor trip_actor) from public;
revoke all on function public.is_terminal(p_state trip_state) from public;
revoke all on function public.ledger_entries_append_only() from public;
revoke all on function public.list_saved_places() from public;
revoke all on function public.my_documents() from public;
revoke all on function public.notify_user(p_user_id uuid, p_title text, p_body text, p_data jsonb) from public;
revoke all on function public.offer_next_candidate(p_trip_id uuid) from public;
revoke all on function public.offer_ttl_seconds() from public;
revoke all on function public.presence_status_now(p_rider_id uuid) from public;
revoke all on function public.prune_track_points() from public;
revoke all on function public.publish_track_point(p_trip_id uuid, p_lng double precision, p_lat double precision, p_accuracy_m real) from public;
revoke all on function public.push_on_offer() from public;
revoke all on function public.push_on_trip_state() from public;
revoke all on function public.raise_sos(p_trip_id uuid, p_lng double precision, p_lat double precision, p_note text) from public;
revoke all on function public.rate_trip(p_trip_id uuid, p_rating smallint, p_comment text) from public;
revoke all on function public.register_rider(p_first_name text, p_phone text, p_licence text, p_plate text, p_vest text, p_class vehicle_class) from public;
revoke all on function public.review_document(p_rider_id uuid, p_kind document_kind, p_approve boolean, p_note text) from public;
revoke all on function public.review_queue() from public;
revoke all on function public.round_fare_rwf(p_amount numeric) from public;
revoke all on function public.search_landmarks(p_query text, p_limit integer) from public;
revoke all on function public.set_trip_payment_kind() from public;
revoke all on function public.shares_active_trip(p_other uuid) from public;
revoke all on function public.suspend_rider(p_rider_id uuid, p_reason text) from public;
revoke all on function public.trip_contact(p_trip_id uuid) from public;
revoke all on function public.trip_rider_card(p_trip_id uuid) from public;
revoke all on function public.trip_rider_position(p_trip_id uuid) from public;
revoke all on function public.trip_transition_system(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb) from public;
revoke all on function public.trip_transition(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb) from public;
revoke all on function public.trips_guard_state() from public;
revoke all on function public.verify_rider(p_rider_id uuid) from public;

-- 7b. Grants, re-applied to the recreated functions.
grant execute on function public.accept_offer(p_offer_id uuid, p_idempotency_key text) to authenticated;
grant execute on function public.accept_offer(p_offer_id uuid, p_idempotency_key text) to service_role;
grant execute on function public.assign_rider_to_trip(p_trip_id uuid, p_rider_id uuid, p_idempotency_key text) to service_role;
grant execute on function public.can_go_online(p_rider_id uuid) to authenticated;
grant execute on function public.can_go_online(p_rider_id uuid) to service_role;
grant execute on function public.commission_rwf(p_fare_rwf integer, p_rate_pct numeric) to authenticated;
grant execute on function public.commission_rwf(p_fare_rwf integer, p_rate_pct numeric) to service_role;
grant execute on function public.complete_trip(p_trip_id uuid, p_actual_distance_m integer, p_idempotency_key text) to authenticated;
grant execute on function public.complete_trip(p_trip_id uuid, p_actual_distance_m integer, p_idempotency_key text) to service_role;
grant execute on function public.create_trip_from_quote(p_quote_id uuid, p_pickup geography, p_pickup_label text, p_pickup_note text, p_dropoff geography, p_dropoff_label text) to authenticated;
grant execute on function public.create_trip_from_quote(p_quote_id uuid, p_pickup geography, p_pickup_label text, p_pickup_note text, p_dropoff geography, p_dropoff_label text) to service_role;
grant execute on function public.create_trip_offer(p_trip_id uuid, p_rider_id uuid, p_rank integer, p_eta_seconds integer, p_ttl_seconds integer, p_idempotency_key text) to service_role;
grant execute on function public.credit_rider_wallet(p_rider_id uuid, p_amount_rwf integer, p_reference text) to service_role;
grant execute on function public.current_fare_policy(p_class vehicle_class) to authenticated;
grant execute on function public.current_fare_policy(p_class vehicle_class) to service_role;
grant execute on function public.decline_offer(p_offer_id uuid) to authenticated;
grant execute on function public.decline_offer(p_offer_id uuid) to service_role;
grant execute on function public.dispatch_pending_trips() to service_role;
grant execute on function public.rider_balance(p_rider_id uuid) to authenticated;
grant execute on function public.rider_balance(p_rider_id uuid) to service_role;
grant execute on function public.expire_stale_offers() to service_role;
grant execute on function public.fare_policy_for_quote(p_quote_id uuid) to authenticated;
grant execute on function public.fare_policy_for_quote(p_quote_id uuid) to service_role;
grant execute on function public.final_fare_rwf(p_quoted_rwf integer, p_quoted_distance_m integer, p_actual_distance_m integer, p_per_km_rwf integer) to authenticated;
grant execute on function public.final_fare_rwf(p_quoted_rwf integer, p_quoted_distance_m integer, p_actual_distance_m integer, p_per_km_rwf integer) to service_role;
grant execute on function public.find_candidate_riders(p_pickup geography, p_class vehicle_class, p_radius_m integer, p_limit integer) to service_role;
grant execute on function public.find_candidates_for_trip(p_trip_id uuid, p_radius_m integer, p_limit integer) to service_role;
grant execute on function public.is_legal_transition(p_from trip_state, p_to trip_state, p_actor trip_actor) to authenticated;
grant execute on function public.is_legal_transition(p_from trip_state, p_to trip_state, p_actor trip_actor) to service_role;
grant execute on function public.is_terminal(p_state trip_state) to authenticated;
grant execute on function public.is_terminal(p_state trip_state) to service_role;
grant execute on function public.ledger_entries_append_only() to anon;
grant execute on function public.ledger_entries_append_only() to authenticated;
grant execute on function public.ledger_entries_append_only() to service_role;
grant execute on function public.list_saved_places() to authenticated;
grant execute on function public.list_saved_places() to service_role;
grant execute on function public.my_documents() to authenticated;
grant execute on function public.my_documents() to service_role;
grant execute on function public.notify_user(p_user_id uuid, p_title text, p_body text, p_data jsonb) to service_role;
grant execute on function public.offer_next_candidate(p_trip_id uuid) to service_role;
grant execute on function public.offer_ttl_seconds() to authenticated;
grant execute on function public.offer_ttl_seconds() to service_role;
grant execute on function public.presence_status_now(p_rider_id uuid) to authenticated;
grant execute on function public.presence_status_now(p_rider_id uuid) to service_role;
grant execute on function public.prune_track_points() to service_role;
grant execute on function public.publish_track_point(p_trip_id uuid, p_lng double precision, p_lat double precision, p_accuracy_m real) to authenticated;
grant execute on function public.publish_track_point(p_trip_id uuid, p_lng double precision, p_lat double precision, p_accuracy_m real) to service_role;
grant execute on function public.push_on_offer() to anon;
grant execute on function public.push_on_offer() to authenticated;
grant execute on function public.push_on_offer() to service_role;
grant execute on function public.push_on_trip_state() to anon;
grant execute on function public.push_on_trip_state() to authenticated;
grant execute on function public.push_on_trip_state() to service_role;
grant execute on function public.raise_sos(p_trip_id uuid, p_lng double precision, p_lat double precision, p_note text) to authenticated;
grant execute on function public.raise_sos(p_trip_id uuid, p_lng double precision, p_lat double precision, p_note text) to service_role;
grant execute on function public.rate_trip(p_trip_id uuid, p_rating smallint, p_comment text) to authenticated;
grant execute on function public.rate_trip(p_trip_id uuid, p_rating smallint, p_comment text) to service_role;
grant execute on function public.register_rider(p_first_name text, p_phone text, p_licence text, p_plate text, p_vest text, p_class vehicle_class) to authenticated;
grant execute on function public.register_rider(p_first_name text, p_phone text, p_licence text, p_plate text, p_vest text, p_class vehicle_class) to service_role;
grant execute on function public.review_document(p_rider_id uuid, p_kind document_kind, p_approve boolean, p_note text) to service_role;
grant execute on function public.review_queue() to service_role;
grant execute on function public.round_fare_rwf(p_amount numeric) to authenticated;
grant execute on function public.round_fare_rwf(p_amount numeric) to service_role;
grant execute on function public.search_landmarks(p_query text, p_limit integer) to authenticated;
grant execute on function public.search_landmarks(p_query text, p_limit integer) to service_role;
grant execute on function public.set_trip_payment_kind() to anon;
grant execute on function public.set_trip_payment_kind() to authenticated;
grant execute on function public.set_trip_payment_kind() to service_role;
grant execute on function public.shares_active_trip(p_other uuid) to authenticated;
grant execute on function public.shares_active_trip(p_other uuid) to service_role;
grant execute on function public.suspend_rider(p_rider_id uuid, p_reason text) to service_role;
grant execute on function public.trip_contact(p_trip_id uuid) to authenticated;
grant execute on function public.trip_contact(p_trip_id uuid) to service_role;
grant execute on function public.trip_rider_card(p_trip_id uuid) to authenticated;
grant execute on function public.trip_rider_card(p_trip_id uuid) to service_role;
grant execute on function public.trip_rider_position(p_trip_id uuid) to authenticated;
grant execute on function public.trip_rider_position(p_trip_id uuid) to service_role;
grant execute on function public.trip_transition(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb) to authenticated;
grant execute on function public.trip_transition(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb) to service_role;
grant execute on function public.trip_transition_system(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb) to service_role;
grant execute on function public.trips_guard_state() to service_role;
grant execute on function public.verify_rider(p_rider_id uuid) to service_role;

-- 8. Re-assert the revokes. Supabase grants `authenticated` privileges through
-- ALTER DEFAULT PRIVILEGES, so a recreated function can come back executable by
-- roles that were deliberately denied it - the defect this project has already
-- shipped four times.
revoke all on function public.accept_offer(p_offer_id uuid, p_idempotency_key text) from anon;
revoke all on function public.assign_rider_to_trip(p_trip_id uuid, p_rider_id uuid, p_idempotency_key text) from anon;
revoke all on function public.assign_rider_to_trip(p_trip_id uuid, p_rider_id uuid, p_idempotency_key text) from authenticated;
revoke all on function public.can_go_online(p_rider_id uuid) from anon;
revoke all on function public.can_go_online_internal(p_rider_id uuid) from anon;
revoke all on function public.can_go_online_internal(p_rider_id uuid) from authenticated;
revoke all on function public.commission_rwf(p_fare_rwf integer, p_rate_pct numeric) from anon;
revoke all on function public.complete_trip(p_trip_id uuid, p_actual_distance_m integer, p_idempotency_key text) from anon;
revoke all on function public.create_trip_from_quote(p_quote_id uuid, p_pickup geography, p_pickup_label text, p_pickup_note text, p_dropoff geography, p_dropoff_label text) from anon;
revoke all on function public.create_trip_offer(p_trip_id uuid, p_rider_id uuid, p_rank integer, p_eta_seconds integer, p_ttl_seconds integer, p_idempotency_key text) from anon;
revoke all on function public.create_trip_offer(p_trip_id uuid, p_rider_id uuid, p_rank integer, p_eta_seconds integer, p_ttl_seconds integer, p_idempotency_key text) from authenticated;
revoke all on function public.credit_rider_wallet(p_rider_id uuid, p_amount_rwf integer, p_reference text) from anon;
revoke all on function public.credit_rider_wallet(p_rider_id uuid, p_amount_rwf integer, p_reference text) from authenticated;
revoke all on function public.current_fare_policy(p_class vehicle_class) from anon;
revoke all on function public.decline_offer(p_offer_id uuid) from anon;
revoke all on function public.dispatch_pending_trips() from anon;
revoke all on function public.dispatch_pending_trips() from authenticated;
revoke all on function public.rider_balance(p_rider_id uuid) from anon;
revoke all on function public.rider_balance_internal(p_rider_id uuid) from anon;
revoke all on function public.rider_balance_internal(p_rider_id uuid) from authenticated;
revoke all on function public.expire_stale_offers() from anon;
revoke all on function public.expire_stale_offers() from authenticated;
revoke all on function public.fare_policy_for_quote(p_quote_id uuid) from anon;
revoke all on function public.final_fare_rwf(p_quoted_rwf integer, p_quoted_distance_m integer, p_actual_distance_m integer, p_per_km_rwf integer) from anon;
revoke all on function public.find_candidate_riders(p_pickup geography, p_class vehicle_class, p_radius_m integer, p_limit integer) from anon;
revoke all on function public.find_candidate_riders(p_pickup geography, p_class vehicle_class, p_radius_m integer, p_limit integer) from authenticated;
revoke all on function public.find_candidates_for_trip(p_trip_id uuid, p_radius_m integer, p_limit integer) from anon;
revoke all on function public.find_candidates_for_trip(p_trip_id uuid, p_radius_m integer, p_limit integer) from authenticated;
revoke all on function public.is_legal_transition(p_from trip_state, p_to trip_state, p_actor trip_actor) from anon;
revoke all on function public.is_terminal(p_state trip_state) from anon;
revoke all on function public.list_saved_places() from anon;
revoke all on function public.my_documents() from anon;
revoke all on function public.notify_user(p_user_id uuid, p_title text, p_body text, p_data jsonb) from anon;
revoke all on function public.notify_user(p_user_id uuid, p_title text, p_body text, p_data jsonb) from authenticated;
revoke all on function public.offer_next_candidate(p_trip_id uuid) from anon;
revoke all on function public.offer_next_candidate(p_trip_id uuid) from authenticated;
revoke all on function public.offer_ttl_seconds() from anon;
revoke all on function public.presence_status_now(p_rider_id uuid) from anon;
revoke all on function public.prune_track_points() from anon;
revoke all on function public.prune_track_points() from authenticated;
revoke all on function public.publish_track_point(p_trip_id uuid, p_lng double precision, p_lat double precision, p_accuracy_m real) from anon;
revoke all on function public.raise_sos(p_trip_id uuid, p_lng double precision, p_lat double precision, p_note text) from anon;
revoke all on function public.rate_trip(p_trip_id uuid, p_rating smallint, p_comment text) from anon;
revoke all on function public.register_rider(p_first_name text, p_phone text, p_licence text, p_plate text, p_vest text, p_class vehicle_class) from anon;
revoke all on function public.review_document(p_rider_id uuid, p_kind document_kind, p_approve boolean, p_note text) from anon;
revoke all on function public.review_document(p_rider_id uuid, p_kind document_kind, p_approve boolean, p_note text) from authenticated;
revoke all on function public.review_queue() from anon;
revoke all on function public.review_queue() from authenticated;
revoke all on function public.round_fare_rwf(p_amount numeric) from anon;
revoke all on function public.search_landmarks(p_query text, p_limit integer) from anon;
revoke all on function public.shares_active_trip(p_other uuid) from anon;
revoke all on function public.suspend_rider(p_rider_id uuid, p_reason text) from anon;
revoke all on function public.suspend_rider(p_rider_id uuid, p_reason text) from authenticated;
revoke all on function public.trip_contact(p_trip_id uuid) from anon;
revoke all on function public.trip_rider_card(p_trip_id uuid) from anon;
revoke all on function public.trip_rider_position(p_trip_id uuid) from anon;
revoke all on function public.trip_transition(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb) from anon;
revoke all on function public.trip_transition_system(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb) from anon;
revoke all on function public.trip_transition_system(p_trip_id uuid, p_to trip_state, p_idempotency_key text, p_meta jsonb) from authenticated;
revoke all on function public.trips_guard_state() from anon;
revoke all on function public.trips_guard_state() from authenticated;
revoke all on function public.verify_rider(p_rider_id uuid) from anon;
revoke all on function public.verify_rider(p_rider_id uuid) from authenticated;

-- 9. Policies restored.
create policy presence_owner_all on public.rider_presence
  for all
  using (rider_id = auth.uid())
  with check (
    rider_id = auth.uid()
    and (
      status <> 'online'::rider_status
      or presence_status_now(auth.uid()) = 'online'::rider_status
      or (
        exists (
          select 1 from public.riders d
           where d.id = auth.uid() and d.verification = 'verified'::verification_status
        )
        and can_go_online(auth.uid())
      )
    )
  );

create policy profiles_select_trip_partner on public.profiles
  for select
  using (shares_active_trip(id));

-- 10. Storage: the documents bucket and its policies.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
select 'rider-documents', 'rider-documents', public, file_size_limit, allowed_mime_types
  from storage.buckets where id = 'driver-documents'
on conflict (id) do nothing;

update storage.objects set bucket_id = 'rider-documents' where bucket_id = 'driver-documents';

-- The old bucket is deliberately left in place, empty. Supabase refuses a
-- direct DELETE from storage.buckets ("Use the Storage API instead"), and an
-- empty bucket nothing references is a tidiness problem, not a correctness one.
-- Remove it from the dashboard if it bothers you.

-- The policies name the bucket as a literal, so they have to be rewritten
-- rather than renamed.
drop policy if exists driver_docs_insert_own on storage.objects;
drop policy if exists driver_docs_select_own on storage.objects;
drop policy if exists driver_docs_update_own on storage.objects;

create policy rider_docs_insert_own on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'rider-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy rider_docs_select_own on storage.objects
  for select to authenticated
  using (
    bucket_id = 'rider-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy rider_docs_update_own on storage.objects
  for update to authenticated
  using (
    bucket_id = 'rider-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
